// Generated by scripts/sync-version.mjs — do not edit by hand.
// One source of truth for the version; 9.18.2 in v9 fixed the reload loop
// caused by version.json and the bundle disagreeing.
export const VERSION = '3.0.0';
